import { Inter } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

import Cart from "@/components/Cart";
import { CartProvider } from "@/provider/cart-provider";
// export const dynamicParams = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Cart />
          <Header />
          <div className="mx-auto py-5 px-5 sm:px-20 lg:px-32 2xl:px-52 relative ">
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
